### ISSUE TITLE
Input data / headers not working

### ISSUE THREAD

**Issue by leso-kn** [skonagaya/HTTP-Push#15] opened 2017-08-12 12:46 UTC
I happen to have an issue with any of the POST, PUT and DELETE methods.
They don't seem to accept any input data nor do they use the custom headers i specify

<img src="https://user-images.githubusercontent.com/7886606/29240810-d8b786dc-7f6c-11e7-8f61-ea39872746f4.png" width=200px/> <img src="https://user-images.githubusercontent.com/7886606/29240811-e562e07a-7f6c-11e7-95b8-97776ba5d30d.png" width=200px/>

Both requests just give me an empty `php://input` and `$_SERVER` without `HTTP_KEY`

I tested my server-side code with curl, it's working. Appears there are some issues with the new update?
Also i can't launch the app on my pebble anymore, i'm using Pebble Classic with firmware v3.12.3.

**Comment by skonagaya** [comment] 2017-08-12 15:28
I'll take a look.

What do you see when you launch the app? Does it crash immediately?

**Comment by skonagaya** [comment] 2017-08-12 15:56
So 3 items I want to address:

1. **Headers not working**: I was able to reproduce this. Headers were not being sent in the configuration page. I just pushed out a fix for this and it's working for me. Remember to use Access Control headers on your POST and OPTIONS calls.
2. **Doesn't accept input data**: I'm not able to reproduce this. Do you not receive a request on your server? Or is the JSON data not there? 
3. **Can't launch on Pebble Classic v3.12.3**: I pushed out a new version to hopefully address this. I was able to reproduce and fix it on an emulator, but I'm not able to test on an actual watch since I don't own a classic Pebble.

**Comment by skonagaya** [comment] 2017-08-12 21:17
Actually, I've removed the TEST button from the configuration page. This is done to provide a more **consistent** testing/troubleshooting experience for users.

The behavior of the http call on the configuration page and http call on the watch is different. The configuration page uses a browser agent (requires CORS headers on servers), where calls from the pebble watch doesn't.

To test requests, deploy your requests and trigger them on the watch itself.

**Comment by leso-kn** [comment] 2017-08-13 00:21
Thanks for your reply, i'll answer in more detail tomorrow (it's night here)
When i try to launch the app, it just plays that short page transition animation, but the pebble keeps showing the home screen (or jumps to it if you used quicklaunch from a watchface).
My server receives the request, but input data is missing.
And thanks for the new build, i'll check it out tomorrow!

**Comment by leso-kn** [comment] 2017-08-13 17:53
I've tested it now, app launches on my watch, input data is being used - everything works fine, thank you! :)

**Comment by skonagaya** [comment] 2017-08-14 02:04
Awesome!

**Closed as completed by skonagaya** 2017-08-14 02:04 UTC
